### ISSUE TITLE
"onScrollChange is not a function" in version 1.3.9

### ISSUE THREAD

**Issue by Nico142** [TechStark/react-dnd-scrolling#40]
After updating from 1.3.8 to 1.3.9 the scrolling doesn't work anymore and I receive this error:
```
TypeError: onScrollChange is not a function
    at tick (react-dnd-scrolling.js?v=c05df4f0:391:9)
```
And the error is pointing at:
```
onScrollChange(newLeft, newTop);
```

I'm using the base example with `withScrolling`.  
Packages version:
- react-dnd **15.1.2**
- react **18.3.1**

**Comment by ttt43ttt** [comment]
@Nico142 This issue is fixed in 1.3.10. Sorry for the inconvenience.
